[package]
name = "fog-ledger-enclave-edl"
version = "1.1.0-pre5"
authors = ["MobileCoin"]
edition = "2018"
links = "ledger_enclave_edl"
license = "GPL-3.0"

[build-dependencies]
mc-util-build-script = { path = "../../../../mobilecoin/util/build/script" }
cargo-emit = "0.1"
