Vagrant.configure("2") do |config|
  config.vm.box = "mobilecoin"
  config.vm.network "private_network", ip: "192.168.50.4"
  config.vm.synced_folder "../../..", "/Users/vagrant/internal", type: "nfs"
  config.vm.provider "virtualbox"
end
