[package]
name = "fog-view-enclave-edl"
version = "1.1.2"
authors = ["MobileCoin"]
edition = "2018"
links = "view_enclave_edl"
license = "GPL-3.0"

[build-dependencies]
mc-util-build-script = { path = "../../../../mobilecoin/util/build/script" }

cargo-emit = "0.1"
