Vagrant.configure("2") do |config|
  config.vm.box = "macinbox"
  config.vm.network "private_network", ip: "192.168.50.5"
  config.vm.synced_folder "../../../../..", "/Users/vagrant/internal", type: "nfs"
  config.vm.provider "virtualbox"

  config.vm.provision "file", source: "files/.profile", destination: "$HOME/.profile"
  config.vm.provision "file", source: "files/.profile", destination: "$HOME/.zprofile"

  config.vm.provision "shell", privileged: false, inline:
      "cd /Users/vagrant/internal/tools/macos/vm/provisioning/mc-box/guest && ./provision /Users/vagrant/internal"
end
